// import './globals.css'
// 'use client';
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>Header</h1>
        </header>

        {children}

        <footer>
          <h1>footer</h1>
        </footer>
      </body>
    </html>
  );
}
